DROP TABLE IF EXISTS `proyectos`;
CREATE TABLE `proyectos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `titulo` varchar(255) NOT NULL,
  `imagen` varchar(255) DEFAULT NULL,
  `descripcion` longtext NOT NULL,
  `fechaProyecto` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb3;
LOCK TABLES `proyectos` WRITE;
INSERT INTO `proyectos` VALUES (24,'Ecomerce put','ecommerce.png','Cras vitae placerat velit. Curabitur vel diam justo. Praesent sagittis, tellus sit amet maximus venenatis, lorem sapien placerat dui, ac imperdiet enim tortor sed tellus. Praesent eleifend, orci ut ullamcorper tincidunt, quam leo fermentum est, a congue diam erat sed ex. Proin at neque eleifend, posuere risus nec, lobortis mi. Curabitur vitae metus sed nibh molestie dignissim. Sed quis maximus ex. Maecenas finibus lacinia massa vel vehicula. Donec eleifend nisi a mi laoreet, vel varius velit malesuada. Mauris vel risus sed leo placerat maximus sit amet id odio. Aliquam accumsan id turpis quis blandit. Vestibulum viverra justo in nunc luctus posuere. Nam pretium ligula eget lectus dignissim, lobortis vehicula justo malesuada. Integer sit amet pellentesque nulla','2024-01-01'),(25,'Administración citas','adm_citas.png','Vivamus faucibus lorem id nisl vehicula, eu mattis nisl posuere. Nam at nulla commodo, gravida augue sed, laoreet eros. Nullam pellentesque dictum ante, eget fermentum sapien porta in. Mauris ut sodales lectus, volutpat vestibulum augue. Cras pulvinar dapibus tortor ac efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus quis erat orci. Morbi vitae urna sit amet urna vestibulum ultricies. Integer et neque in urna pretium euismod sed non arcu. Nunc at lectus at eros pharetra porta. Suspendisse eros diam, commodo quis pretium ut, cursus luctus ipsum','2023-12-07'),(26,'Administrador de tareas','task-manager.png','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam faucibus suscipit bibendum. Nunc eget sollicitudin dolor. Phasellus cursus laoreet ante quis eleifend. Phasellus sagittis rhoncus magna. Morbi ex tellus, consequat vel felis a, volutpat accumsan magna. Sed congue justo et blandit ullamcorper. Aenean at ligula et massa fermentum scelerisque. Suspendisse potenti. Morbi laoreet dui vitae turpis vulputate, luctus tincidunt mi tempus. Nunc consectetur rhoncus finibus. Aliquam dapibus condimentum lectus eget laoreet. Vestibulum id auctor mauris, a commodo arcu.','2023-11-08'),(27,'Portafolio empresa','web_empresa.png','Pellentesque sit amet felis imperdiet, viverra nunc eu, rutrum ipsum. Proin quis eros iaculis, posuere tellus a, efficitur sapien. Nulla eu rhoncus odio. Integer ut viverra ligula. Suspendisse potenti. Vestibulum porta tempus arcu. Pellentesque neque dui, vehicula vitae ipsum ac, elementum placerat ante. In odio diam, porttitor quis cursus eu, elementum non nulla. Nam bibendum eu metus eu auctor.\nNulla facilisi. Pellentesque sed risus a quam tincidunt accumsan nec sed neque. Cras malesuada ultricies dolor eu pellentesque. Ut rhoncus blandit nunc in suscipit. Sed velit urna, volutpat a pretium at, interdum non dui. Curabitur vehicula lectus justo, in egestas nisi fringilla dictum. Sed et pulvinar risus','2024-01-09');
UNLOCK TABLES;